SET AUTOCOMMIT FALSE;

INSERT INTO PERSON VALUES(NEXT VALUE FOR PERSON_SEQ, 'Name1');
INSERT INTO PERSON VALUES(NEXT VALUE FOR PERSON_SEQ, 'Name2');

--insert into USERS (ID, USERNAME) VALUES(NEXT/CURRENT VALUE FOR USER_SEQ, 'USER 1');

COMMIT;
