SET AUTOCOMMIT FALSE;

INSERT INTO PERSON VALUES(NEXT VALUE FOR PERSON_SEQ, 'LastName1', 'FirstName1');
INSERT INTO PERSON VALUES(NEXT VALUE FOR PERSON_SEQ, 'LastName2', 'FirstName2');

--insert into USERS (ID, USERNAME) VALUES(NEXT/CURRENT VALUE FOR USER_SEQ, 'USER 1');

COMMIT;
