-- HSQLDB / H2
DROP TABLE IF EXISTS PERSON CASCADE;
DROP SEQUENCE IF EXISTS PERSON_SEQ;

CREATE TABLE PERSON(
    ID BIGINT NOT NULL,
    NAME VARCHAR(25) NOT NULL
);

ALTER TABLE PERSON ADD CONSTRAINT PERSON_PK PRIMARY KEY (ID);
ALTER TABLE PERSON ADD CONSTRAINT PERSON_NAME_UNQ UNIQUE (NAME);
--CREATE UNIQUE INDEX PERSON_NAME_UNQ ON PERSON (NAME);

ALTER TABLE PERSON ADD CONSTRAINT PERSON_CK_NAME CHECK(TRIM(NAME) <> ' ');

CREATE SEQUENCE PERSON_SEQ START WITH 1 INCREMENT BY 1;
-- AS BIGINT
