-- HSQLDB / H2
DROP TABLE IF EXISTS PERSON CASCADE;
DROP SEQUENCE IF EXISTS PERSON_SEQ;

CREATE TABLE PERSON(
    ID BIGINT NOT NULL,
    NAME VARCHAR(25) NOT NULL,
    VORNAME VARCHAR(25)
);

ALTER TABLE PERSON ADD CONSTRAINT PERSON_PK PRIMARY KEY (ID);
ALTER TABLE PERSON ADD CONSTRAINT PERSON_NAME_UNQ UNIQUE (NAME, VORNAME);
--CREATE UNIQUE INDEX PERSON_NAME_UNQ ON PERSON (NAME, VORNAME);

ALTER TABLE PERSON ADD CONSTRAINT PERSON_CK_NACHNAME CHECK(TRIM(NAME) <> ' ');

CREATE SEQUENCE PERSON_SEQ START WITH 1 INCREMENT BY 1;
-- AS BIGINT